InformedSolutions/JAQU-CAZ-Tariff-Service

pom.xml
src/it/java/uk/gov/caz/tariff/CazTestIT.java
src/main/java/uk/gov/caz/tariff/amazonaws/StreamLambdaHandler.java

Add security and thundra updates to SIT

Add security and thundra updates to SIT

---

pom.xml
src/main/java/uk/gov/caz/tariff/controller/DbSchemaMigrationControllerApi.java
src/main/java/uk/gov/caz/tariff/controller/DbSchemaMigrationControllerApiSpec.java
src/main/java/uk/gov/caz/tariff/util/LiquibaseWrapper.java
src/main/resources/application.yml
src/test/java/uk/gov/caz/tariff/controller/DbSchemaMigrationControllerTest.java

spread the proposed change from vccs over

add db schema migration endpoint

---

.drone.yml

Adds separated DB migration step in development environment

Add db migration step to deployments in dev

---

.drone.yml

Adds separate DB migration step for performance optimisation

Update pipeline to production with separate DB migrations

---

pom.xml
src/it/java/uk/gov/caz/tariff/CazTestIT.java
src/it/java/uk/gov/caz/tariff/controller/CleanAirZonesControllerTestIT.java
src/main/java/uk/gov/caz/tariff/controller/CleanAirZonesControllerApiSpec.java
src/main/java/uk/gov/caz/tariff/controller/DbSchemaMigrationControllerApiSpec.java
src/test/java/uk/gov/caz/tariff/controller/DbSchemaMigrationControllerTest.java

MSSA - Make Sonar Sublime Again - fixing MediaType and LiquibaseWrapper tests

NON-JIRA MSSA - Make Sonar Sublime Again - fixing MediaType and LiquibaseWrapper tests

---

.drone.yml

Add UAT steps to drone pipeline with recompilation step

Add UAT steps to drone pipeline

---

src/it/java/uk/gov/caz/tariff/TariffRepositoryTestIT.java
src/it/java/uk/gov/caz/tariff/controller/CleanAirZonesControllerTestIT.java
src/main/java/uk/gov/caz/tariff/dto/Tariff.java
src/main/java/uk/gov/caz/tariff/service/TariffRepository.java
src/test/java/uk/gov/caz/tariff/controller/CleanAirZonesControllerTest.java
src/test/java/uk/gov/caz/tariff/service/TariffRepositoryTest.java

JIRA: https://eaflood.atlassian.net/browse/CAZ-2389

[CAZ-2389] active_charge_start_time property exposed in CAZ tariff endpoint

---

.drone2.yml
pom.xml

CAZB-1177-AWS Restructure - updated drone2.yml with deployment pipeline

CAZB-1177-AWS Restructure - updated drone2.yml with deployment pipeline

---

.drone2.yml

Updated drone file

---

src/it/java/uk/gov/caz/tariff/controller/CleanAirZonesControllerTestIT.java
src/it/resources/data/json/sample-tariff.json
src/it/resources/data/json/tariff.json
src/it/resources/data/sql/sample-data.sql
src/main/java/uk/gov/caz/tariff/dto/InformationUrls.java
src/main/java/uk/gov/caz/tariff/service/TariffRepository.java
src/main/resources/application.yml
src/main/resources/db/changelog/changes/0018-1.0-drop_obsolete_link_columns.yaml
src/test/java/uk/gov/caz/tariff/controller/CleanAirZonesControllerTest.java
src/test/java/uk/gov/caz/tariff/service/TariffRepositoryTest.java

CAZB-1185 Remove unused Tariff links: emissions, pricing, pay-caz, financial assistance, hours of operations.

CAZB-1185 Remove unused Tariff links: emissions, pricing, pay-caz, financial assistance, hours of operations.

---

.drone2.yml

updated alpine image version

---

.drone2.yml

fix drone build issue

---

.drone2.yml

updated controlled environment changes

updated controlled environment changes

---

pom.xml
src/it/java/uk/gov/caz/tariff/controller/CleanAirZonesControllerTestIT.java
src/it/resources/data/json/sample-clean-air-zones.json
src/it/resources/data/sql/sample-data.sql
src/main/java/uk/gov/caz/tariff/service/CleanAirZonesRepository.java
src/main/resources/db/changelog/changes/0019-1.0-add_operator_name.yaml
src/test/java/uk/gov/caz/tariff/service/CleanAirZonesRepositoryTest.java

Jira Card: https://eaflood.atlassian.net/browse/CAZ-2849
Added CAZ OperaorName to the `/clean-air-zones` endpoint response.

[CAZ-2849] CleanAirZone OperatorName to response

---

.drone2.yml

Promote Tariffs RC1.4.0 to new AWS infrastructure

Promote Tariffs RC1.4.0 to new AWS infrastructure

---

.drone2.yml

Prod branch name correction

---

src/main/resources/db/changelog/changes/0020-1.0-bath-links.yaml

https://eaflood.atlassian.net/browse/CAZB-2231

CAZB-2231 Bath links go to liquibase

---

src/main/resources/db/changelog/changes/0019-1.0-add_operator_name.yaml
src/main/resources/db/changelog/changes/0020-1.0-bath-caz.yaml

Altered the changesets to make sure that any exceptions arising from data already having been inserted are handled. These changeset alterations will cause conflicts on dev so I will delete the last two rows from the changelog before merging this into develop.

[CAZB-2231] make Bath tariff and link additions idempotent

---

src/main/resources/application.yml

https://eaflood.atlassian.net/browse/CAZB-3144

[CAZB-3144] set correlation id logger to the info level

---

src/main/resources/db/changelog/changes/0023-1.0-remove-leeds.yaml

https://eaflood.atlassian.net/browse/CAZB-3358

[CAZB-3358] Remove Leeds from the db

---

pom.xml
src/main/java/uk/gov/caz/tariff/amazonaws/StreamLambdaHandler.java

[CAZB-3974] Update stream lambda handler

---

src/main/resources/db/changelog/changes/0024.1.0-birmingham-update-boundary-url.yaml

Jira Card: https://eaflood.atlassian.net/browse/CAZB-2127
Additionally fixed: https://eaflood.atlassian.net/browse/CAZB-3879

[CAZB-2127] Amend Birmingham 'Zone Boundary' URL

---

src/it/resources/data/sql/sample-data.sql
src/main/resources/db/changelog/changes/0027.1-0-add-configuration-columns-for-dynamic-display.yaml

Jira Card :https://eaflood.atlassian.net/browse/CAZB-4323

[CAZB-4323] Add new configuration item columns

---

pom.xml
src/it/java/uk/gov/caz/tariff/CazTestIT.java
src/it/java/uk/gov/caz/tariff/TariffRepositoryTestIT.java
src/it/java/uk/gov/caz/tariff/controller/CleanAirZonesControllerTestIT.java
src/it/java/uk/gov/caz/tariff/util/JsonReader.java
src/it/resources/data/json/birmingham-tariff.json
src/it/resources/data/json/clean-air-zones.json
src/it/resources/data/json/sample-clean-air-zones.json
src/it/resources/data/json/sample-tariff.json
src/it/resources/data/sql/sample-data.sql
src/main/java/uk/gov/caz/tariff/dto/InformationUrls.java
src/main/java/uk/gov/caz/tariff/dto/Tariff.java
src/main/java/uk/gov/caz/tariff/service/CleanAirZonesRepository.java
src/main/java/uk/gov/caz/tariff/service/RepositoryUtils.java
src/main/java/uk/gov/caz/tariff/service/TariffRepository.java
src/main/resources/application.yml
src/test/java/uk/gov/caz/tariff/controller/CleanAirZonesControllerTest.java
src/test/java/uk/gov/caz/tariff/service/CleanAirZonesRepositoryTest.java
src/test/java/uk/gov/caz/tariff/service/TariffRepositoryTest.java

https://eaflood.atlassian.net/browse/CAZB-4324

[CAZB-4324] Update `CleanAirZones` and `Tariff` endpoints

---

src/main/java/uk/gov/caz/tariff/service/CleanAirZonesRepository.java
src/test/java/uk/gov/caz/tariff/service/CleanAirZonesRepositoryTest.java

https://eaflood.atlassian.net/browse/CAZB-4324
```
for ease of use please return list of CAZes already sorted (ASC) by displayOrder where applicable
```

[CAZB-4323] Order cazes by `display_order`

---

src/main/resources/db/changelog/changes/0028.1-0-update-caz-display-order.yaml

Jira Card: https://eaflood.atlassian.net/browse/CAZB-4323
Updated wrong display order set in: https://github.com/InformedSolutions/JAQU-CAZ-Tariff-Service/commit/1f571c0e58fcb4bcbe326734270976430b19f291

[CAZB-4323] Fix display order for Birmingham CAZ

---

pom.xml
src/it/java/uk/gov/caz/tariff/TariffRepositoryTestIT.java
src/it/resources/data/sql/sample-data.sql
src/main/java/uk/gov/caz/tariff/controller/CleanAirZonesController.java
src/main/java/uk/gov/caz/tariff/dto/Tariff.java
src/main/java/uk/gov/caz/tariff/service/CleanAirZonesRepository.java
src/main/java/uk/gov/caz/tariff/service/TariffRepository.java
src/main/resources/application.yml
src/test/java/uk/gov/caz/tariff/controller/CleanAirZonesControllerTest.java
src/test/java/uk/gov/caz/tariff/service/CleanAirZonesRepositoryTest.java
src/test/java/uk/gov/caz/tariff/service/TariffRepositoryTest.java

JIRA Card: https://eaflood.atlassian.net/browse/CAZB-4473

[CAZB-4473] Added directDebitStartDate attribute

---

src/main/resources/db/changelog/changes/0032-1.0-update-portsmouth-operator-name.yaml

Update Portsmouth operator name to include City Council

[CAZB-4331] Update Portsmouth operator name

---

pom.xml

Log request ids in application logs

[CAZB-4623] Log request ids in application logs

---

src/main/resources/logback-spring.xml

Add Spring logback configuration to use commons libs pattern.

[CAZB-4623] Add logback conf

---

src/main/resources/db/changelog/changes/0033-1.0-update-portsmouth-dates.yaml

Update Portsmouth charge date and start date text

[CAZB-4782] Update Portsmouth charge date and start date text

---

src/main/resources/db/changelog/changes/0035-1.0-update-bcc-active-charge-start-date.yaml

[CAZB-4952] Update BCC active charge start date

[CAZB-4952] Update BCC active charge start date

---

pom.xml

Jira Card: https://eaflood.atlassian.net/browse/CAZB-4974

[CAZB-4974] Upgrade springboot to 2.4.6
